site_name: CS-Learning
site_url: https://guotree.github.io
site_author: guotree
site_description: CS-Learning

repo_url: https://github.com/guotree/CS-Learning
repo_name: CS-Learning

nav:
  - Introduction: "index.md"
  - Programming:
    - "Summary": "programming/summary.md"
    - "Crash Course Notes": "notes/CrashCourseCS.md"
  - Computer Architecture:
    - "Summary": "architecture/summary.md"
  - Algorithms and Data Structures:
    - "Summary": "algorithms/summary.md"
  - "Math for CS":
    - "Summary": "math/summary.md"
  - "Operating Systems":
    - "Summary": "operating-systems/summary.md"
  - "Computer Networking":
    - "Summary": "networking/summary.md"
  - "Databases":
    - "Summary": "databases/summary.md"
  - "Languages and Compilers":
    - "Summary": "languages/summary.md"
  - "Distributed Systems":
    - "Summary": "distributed-systems/summary.md"
  - "Artificial Intelligence":
    - "Summary": "ai/summary.md"
  - "Others":
    - "Summary": "others/summary.md"

theme:
  icon: 
    logo: material/robot-excited-outline
    repo: fontawesome/brands/github
  favicon: assets/robot-excited-outline.svg
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - header.autohide
    - navigation.tracking
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate
  language: en
  custom_dir: overrides
edit_uri: edit/main/docs

copyright: © 2024 GUOTREE Copyright
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/chirui-guo-3ab4a8101
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/guotree
      name: GitHub

plugins:
  - search:
      lang:
        - en
        - zh
      enable_anchors: true
  - tags
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list 
  - toc:
      permalink: true
  - pymdownx.highlight:
      linenums: true
      auto_title: true
  - pymdownx.superfences
  - meta
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html


extra_javascript:
  - https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js
  
extra_css:
  - stylesheets/extra.css

google_analytics: 
  - 'UA-35232574'
  - 'auto'