site_name: CS-Learning
site_url: https://guotree.github.io
site_author: guotree
site_description: CS-Learning

repo_url: https://github.com/guotree/CS-Learning
repo_name: CS-Learning

nav:
  - Introduction: "index.md"
  - Resources:
    - Programming: "resources/programming.md"
    - Computer Architecture: "resources/architecture.md"
    - Algorithms and Data Structures: "resources/algorithms.md"
    - Math for CS: "resources/math.md"
    - Operating Systems: "resources/operating-systems.md"
    - Computer Networking: "resources/networking.md"
    - Databases: "resources/databases.md"
    - Languages and Compilers: "resources/languages.md"
    - Distributed Systems: "resources/distributed-systems.md"
    - Artificial Intelligence: "resources/ai.md"
    - Others: "resources/others.md"
  - Notes:
    - Intro: 
      - "notes/intro/CrashCourseCS/CrashCourseCS.md"
    # - Programming: 
    #   - "notes/programming/templates.md"
    # - Computer Architecture: 
    #   - "notes/architecture/templates.md"
    # - Algorithms and Data Structures: 
    #   - "notes/algorithms/templates.md"
    # - Math for CS:
    #   - "notes/math/templates.md"
    # - Operating Systems:
    #   - "notes/operating-systems/templates.md"
    # - Computer Networking:
    #   - "notes/networking/templates.md"
    # - Databases:
    #   - "notes/databases/templates.md"
    # - Languages and Compilers:
    #   - "notes/languages/templates.md"
    # - Distributed Systems:
    #   - "notes/distributed-systems/templates.md"
    - Artificial Intelligence:
      - Harvard CS109 | HarvardX Data Science:
        - "notes/ai/Harvard-Data-Science/README.md"
        - "notes/ai/Harvard-Data-Science/01-R_Basics.md"
        - "notes/ai/Harvard-Data-Science/02-Visualization.md"
        - "notes/ai/Harvard-Data-Science/03-Probability.md"
        - "notes/ai/Harvard-Data-Science/04-Inference_and_Modeling.md"
        - "notes/ai/Harvard-Data-Science/05-Productivity_Tools.md"
        - "notes/ai/Harvard-Data-Science/06-Wrangling.md"
    # - Others:
    #   - "notes/others/templates.md"
  - Links: "links.md" 
theme:
  icon: 
    logo: material/robot-excited-outline
    repo: fontawesome/brands/github
  favicon: assets/robot-excited-outline.svg
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - header.autohide
    - navigation.tracking
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.code.annotate
  language: en
  custom_dir: overrides
edit_uri: edit/main/docs

copyright: Copyright &copy; 2024 GUOTREE

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/guotree
      name: GitHub

plugins:
  - search:
      lang:
        - en
        - zh
      enable_anchors: true
  - tags
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - toc:  
      permalink: true
  - meta
  - admonition
  - attr_list
  - md_in_html


extra_javascript:
  - https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  
extra_css:
  - stylesheets/extra.css

google_analytics: 
  - 'UA-35232574'
  - 'auto'